model_name_or_path: models/Qwen3-8B-Instruct-2507
adapter_name_or_path: null
cache_dir: .cache/huggingface
template: qwen3_nothink
enable_thinking: false
infer_backend: huggingface
trust_remote_code: true
finetuning_type: lora
quantization_bit: 4
quantization_method: bnb
